class KzPatterns {
  static const kzLocaleDatePatterns = {
    'd': 'd.',
    'E': 'ccc',
    'EEEE': 'cccc',
    'LLL': 'LLL',
    'LLLL': 'LLLL',
    'M': 'L.',
    'Md': 'd.M.',
    'MEd': 'EEE d.M.',
    'MMM': 'LLL',
    'MMMd': 'd. MMM',
    'MMMEd': 'EEE d. MMM',
    'MMMM': 'LLLL',
    'MMMMd': 'd. MMMM',
    'MMMMEEEEd': 'EEEE d. MMMM',
    'QQQ': 'QQQ',
    'QQQQ': 'QQQQ',
    'y': 'y',
    'yM': 'M.y',
    'yMd': 'd.M.y',
    'yMEd': 'EEE d.MM.y',
    'yMMM': 'MMM y',
    'yMMMd': 'd. MMM y',
    'yMMMEd': 'EEE d. MMM y',
    'yMMMM': 'MMMM y',
    'yMMMMd': 'd. MMMM y',
    'yMMMMEEEEd': 'EEEE d. MMMM y',
    'yQQQ': 'QQQ y',
    'yQQQQ': 'QQQQ y',
    'H': 'HH',
    'Hm': 'HH:mm',
    'Hms': 'HH:mm:ss',
    'j': 'HH',
    'jm': 'HH:mm',
    'jms': 'HH:mm:ss',
    'jmv': 'HH:mm v',
    'jmz': 'HH:mm z',
    'jz': 'HH z',
    'm': 'm',
    'ms': 'mm:ss',
    's': 's',
    'v': 'v',
    'z': 'z',
    'zzzz': 'zzzz',
    'ZZZZ': 'ZZZZ',
  };

  static const kzDateSymbols = {
    'NAME': 'kz',
    'ERAS': <dynamic>[
      'f.Kr.',
      'e.Kr.',
    ],
// #enddocregion Date2
    'ERANAMES': <dynamic>[
      'før Kristus',
      'etter Kristus',
    ],
    'NARROWMONTHS': <dynamic>[
      'Қ',
      'А',
      'Н',
      'С',
      'М',
      'М',
      'Ш',
      'Т',
      'Қ',
      'Қ',
      'Қ',
      'Ж',
    ],
    'STANDALONENARROWMONTHS': <dynamic>[
      'Қ',
      'А',
      'Н',
      'С',
      'М',
      'М',
      'Ш',
      'Т',
      'Қ',
      'Қ',
      'Қ',
      'Ж',
    ],
    'MONTHS': <dynamic>[
      'Қаңтар',
      'Ақпан',
      'Наурыз',
      'Сәуір',
      'Мамыр',
      'Маусым',
      'Шілде',
      'Тамыз',
      'Қыркүйек',
      'Қазан',
      'Қараша',
      'Желтоқсан',
    ],
    'STANDALONEMONTHS': <dynamic>[
      'Қаңтар',
      'Ақпан',
      'Наурыз',
      'Сәуір',
      'Мамыр',
      'Маусым',
      'Шілде',
      'Тамыз',
      'Қыркүйек',
      'Қазан',
      'Қараша',
      'Желтоқсан',
    ],
    'SHORTMONTHS': <dynamic>[
      'қаң.',
      'ақп.',
      'нау.',
      'сәу.',
      'мам.',
      'мау.',
      'шіл.',
      'там.',
      'қыр.',
      'қаз.',
      'қар.',
      'жел.',
    ],
    'STANDALONESHORTMONTHS': <dynamic>[
      'қаң.',
      'ақп.',
      'нау.',
      'сәу.',
      'мам.',
      'мау.',
      'шіл.',
      'там.',
      'қыр.',
      'қаз.',
      'қар.',
      'жел.',
    ],
    'WEEKDAYS': <dynamic>[
      'дүйсенбі',
      'сейсенбі',
      'сәрсенбі',
      'бейсенбі',
      'жұма',
      'сенбі',
      'жексенбі',
    ],
    'STANDALONEWEEKDAYS': <dynamic>[
      'дүйсенбі',
      'сейсенбі',
      'сәрсенбі',
      'бейсенбі',
      'жұма',
      'сенбі',
      'жексенбі',
    ],
    'SHORTWEEKDAYS': <dynamic>[
      'дүйсенб',
      'сейсенбі',
      'сәрсенбі',
      'бейсенбі',
      'жұма',
      'сенбі',
      'жексенбі',
    ],
    'STANDALONESHORTWEEKDAYS': <dynamic>[
      'дүй',
      'сей',
      'сәр',
      'бей',
      'жұма',
      'сб',
      'же',
    ],
    'NARROWWEEKDAYS': <dynamic>[
      'Д',
      'С',
      'С',
      'Б',
      'Ж',
      'С',
      'С',
    ],
    'STANDALONENARROWWEEKDAYS': <dynamic>[
      'Д',
      'С',
      'С',
      'Б',
      'Ж',
      'С',
      'С',
    ],
    'SHORTQUARTERS': <dynamic>[
      'K1',
      'K2',
      'K3',
      'K4',
    ],
    'QUARTERS': <dynamic>[
      '1. тоқсан',
      '2. тоқсан',
      '3. тоқсан',
      '4. тоқсан',
    ],
    'AMPMS': <dynamic>[
      'a.m.',
      'p.m.',
    ],
    'DATEFORMATS': <dynamic>[
      'EEEE d. MMMM y',
      'd. MMMM y',
      'd. MMM y',
      'dd.MM.y',
    ],
    'TIMEFORMATS': <dynamic>[
      'HH:mm:ss zzzz',
      'HH:mm:ss z',
      'HH:mm:ss',
      'HH:mm',
    ],
    'AVAILABLEFORMATS': null,
    'FIRSTDAYOFWEEK': 1,
    'WEEKENDRANGE': <dynamic>[
      6,
      7,
    ],
    'FIRSTWEEKCUTOFFDAY': 3,
    'DATETIMEFORMATS': <dynamic>[
      '{1} {0}',
      '{1} \'kl\'. {0}',
      '{1}, {0}',
      '{1}, {0}',
    ],
  };
}
